# Generated by Django 2.1.3 on 2018-12-04 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history_wiki', '0003_remove_category_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='history_wiki.Category'),
            preserve_default=False,
        ),
    ]
