# Generated by Django 2.1.3 on 2018-12-14 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history_wiki', '0005_auto_20181213_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категорія', 'verbose_name_plural': 'категорії'},
        ),
    ]
