# Generated by Django 2.1.3 on 2018-12-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history_wiki', '0002_category_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
    ]
