# Generated by Django 2.1.3 on 2018-12-14 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history_wiki', '0004_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'стаття', 'verbose_name_plural': 'статті'},
        ),
    ]
